[functions]
	external_node_modules = ["astro"]

[[redirects]]
	from = "https://eatmon.netlify.app/*"
	to = "https://eatmon.co/:splat"
	status = 301
	force = true

[[redirects]]
	from = "https://main--eatmon.netlify.app/*"
	to = "https://eatmon.co/:splat"
	status = 301
	force = true

[[redirects]]
	from = "/js/script.js"
	to = "https://plausible.io/js/script.js"
	status = 200

[[redirects]]
	from = "/api/event"
	to = "https://plausible.io/api/event"
	status = 200